kind: pipeline
name: default

steps:
  - name: build
    image: dvitali/builder-tools:latest
    privileged: true
    volumes:
    - name: docker
      path: /var/run/docker.sock
    environment:
      DOCKER_HUB_PASSWORD:
        from_secret: docker_hub_password
    commands:
      - docker login -u dvitali -p $DOCKER_HUB_PASSWORD
      - bash ./build.sh
      - bash ./build.sh -e
volumes:
- name: docker
  host:
    path: /var/run/docker.sock
